name: Publish
on:
    push:
        branches: [ '**' ]
        paths-ignore: [ '**.md' ]
    workflow_call:
        secrets:
            MAVEN_USERNAME:
                required: false
            MAVEN_PASSWORD:
                required: false

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Setup Java
                uses: actions/setup-java@v4
                with:
                    distribution: zulu
                    java-version: 11
                    cache: gradle

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v3

            -   name: Grant execution permission
                run: chmod +x ./gradlew

            -   name: Build and Publish
                run: ./gradlew build publish --no-daemon -PMAVEN_USERNAME=$MAVEN_USERNAME -PMAVEN_PASSWORD=$MAVEN_PASSWORD
